### ISSUE TITLE
leaf-tree--advice-imenu-list--insert-entries-internal is incorrect

### ISSUE THREAD

**Issue by JeremPFT** [conao3/leaf-tree.el#7]
As the comment says: This code based on `imenu-list' (2019/03/15 hash:4600873)
but imenu-list--insert-entries-internal changed (commit b50222378412fbe321622a84cb2b036e084c697a)

`-    (setq imenu-list--line-entries (append imenu-list--line-entries (list entry)))`

`+    (setq imenu-list--line-entries (cons entry imenu-list--line-entries))`

The change has to be reported in leaf-tree--advice-imenu-list--insert-entries-internal.
(imenu-list--line-entries is reversed latter in imenu-list)

Pull request done

**Comment by conao3** [comment]
close due to #8
